# Generated by Django 4.1.1 on 2022-09-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(db_index=True, default='', max_length=255, unique=True),
        ),
    ]
